import type { KeyItem } from '$lib/game/features/keyitems/KeyItem';

export const keyItems: KeyItem[] = [
    {
        id: 'ruby-necklace',
        name: 'Ruby Necklace',
        description: 'Boosts your health by 10%',
        icon: '/items/ruby-necklace.png',
        unlockHint: 'TODO',
        unlockLocation: '/TODO',
    },
    {
        id: 'torch',
        name: 'Torch',
        description: 'TODO',
        icon: '/items/torch.png',
        unlockHint: 'TODO',
        unlockLocation: '/TODO',
    },
    {
        id: 'wooden-shield',
        name: 'Wooden Shield',
        description: 'TODO',
        icon: '/items/wooden-shield.png',
        unlockHint: 'TODO',
        unlockLocation: '/TODO',
    },
    {
        id: 'boots-of-lightness',
        name: 'Boots of Lightness',
        description: 'TODO',
        icon: '/items/boots.png',
        unlockHint: 'TODO',
        unlockLocation: '/TODO',
    },
    {
        id: 'silver-tiara',
        name: 'Silver Tiara',
        description: 'TODO',
        icon: '/items/tiara.png',
        unlockHint: 'TODO',
        unlockLocation: '/TODO',
    },
    {
        id: 'eternal-water',
        name: 'Eternal Water',
        description: 'TODO',
        icon: '/items/eternal-water.png',
        unlockHint: 'TODO',
        unlockLocation: '/TODO',
    },
    {
        id: 'pickaxe',
        name: 'Pickaxe',
        description: 'TODO',
        icon: '/items/pickaxe.png',
        unlockHint: 'TODO',
        unlockLocation: '/TODO',
    },
    {
        id: 'lantern',
        name: 'Lantern',
        description: 'TODO',
        icon: '/items/lantern.png',
        unlockHint: 'TODO',
        unlockLocation: '/TODO',
    },
];
