import type { KeyItem } from '$lib/game/features/keyitems/KeyItem';

export const keyItems: KeyItem[] = [
    {
        id: 'ruby-necklace',
        name: 'Ruby Necklace',
        description: 'Boosts your health by 10%',
        icon: '/items/ruby-necklace.png',
        unlockHint: 'Buried deep in the desert',
        unlockLocation: '/desert/remains/',
    },
    {
        id: 'torch',
        name: 'Torch',
        description: 'Deal 10% more damage',
        icon: '/items/torch.png',
        unlockHint: 'Illuminating a fallen hero',
        unlockLocation: '/desert/statue',
    },
    {
        id: 'wooden-shield',
        name: 'Wooden Shield',
        description: 'Negate 25% of incoming damage',
        icon: '/items/wooden-shield.png',
        unlockHint: 'Surely I can find this in the woods',
        unlockLocation: '/forest/witch',
    },
    {
        id: 'boots-of-lightness',
        name: 'Boots of Lightness',
        description: 'Improve Travel speed by 25%',
        icon: '/items/boots.png',
        unlockHint: 'Made from the silkiest silk',
        unlockLocation: '/forest/spider-den',
    },
    {
        id: 'silver-tiara',
        name: 'Silver Tiara',
        description: 'Increases combat speed by 25%',
        icon: '/items/tiara.png',
        unlockHint: 'Worn by only the prettiest spirits',
        unlockLocation: '/riverlands/docks',
    },
    {
        id: 'eternal-water',
        name: 'Eternal Water',
        description: 'Increases health by 25% ',
        icon: '/items/eternal-water.png',
        unlockHint: 'Locally sourced and organic!',
        unlockLocation: '/riverlands/fountain',
    },
    {
        id: 'pickaxe',
        name: 'Pickaxe',
        description: 'Deal 20% more damage',
        icon: '/items/pickaxe.png',
        unlockHint: 'I want this to be mine...',
        unlockLocation: '/mountains/mine',
    },
    {
        id: 'lantern',
        name: 'Lantern',
        description: 'Speed up your attacks by 25%',
        icon: '/items/lantern.png',
        unlockHint: 'Maybe someone left one behind?',
        unlockLocation: '/mountains/outpost',
    },
];
