import type { Power } from '$lib/game/features/powers/Power';
import { RequirementType } from '$lib/game/tools/requirements/RequirementType';
import { PowerType } from '$lib/game/features/powers/PowerType';

export const powers: Power[] = [
    {
        id: 'deal-5-damage',
        name: 'Deal 5 damage',
        requirement: { type: RequirementType.DamageDealt, amount: 5 },
        icon: 'powers/weapon-small.png',
        type: PowerType.Attack,
        baseBonus: 0.05,
        incrementBonus: 0.05,
        maxCount: Infinity,
    },
    {
        id: 'deal-20-damage',
        name: 'Deal 20 damage',
        requirement: { type: RequirementType.DamageDealt, amount: 20 },
        icon: 'powers/weapon-axe.png',
        type: PowerType.Attack,
        baseBonus: 0.2,
        incrementBonus: 0.2,
        maxCount: Infinity,
    },
    {
        id: 'deal-50-damage',
        name: 'Deal 50 damage',
        requirement: { type: RequirementType.DamageDealt, amount: 50 },
        icon: 'powers/weapon-halberd.png',
        type: PowerType.Attack,
        baseBonus: 0.5,
        incrementBonus: 0.5,
        maxCount: Infinity,
    },
    {
        id: 'take-5-damage',
        name: 'Take 5 damage',
        requirement: { type: RequirementType.DamageTaken, amount: 5 },
        icon: '/powers/shield-small.png',
        type: PowerType.Defense,
        baseBonus: 0.05,
        incrementBonus: 0.05,
        maxCount: Infinity,
    },
    {
        id: 'take-20-damage',
        name: 'Take 20 damage',
        requirement: { type: RequirementType.DamageTaken, amount: 20 },
        icon: '/powers/shield-medium.png',
        type: PowerType.Defense,
        baseBonus: 0.2,
        incrementBonus: 0.2,
        maxCount: Infinity,
    },
    {
        id: 'take-50-damage',
        name: 'Take 50 damage',
        requirement: { type: RequirementType.DamageTaken, amount: 50 },
        icon: '/powers/shield-heroic.png',
        type: PowerType.Defense,
        baseBonus: 0.5,
        incrementBonus: 0.5,
        maxCount: Infinity,
    },
    {
        id: 'defeat-1-monster',
        name: 'Defeat 1 monster',
        requirement: { type: RequirementType.MonstersDefeated, amount: 1 },
        icon: '/powers/skull-small.png',
        type: PowerType.Health,
        baseBonus: 0.05,
        incrementBonus: 0.05,
        maxCount: Infinity,
    },
    {
        id: 'defeat-5-monsters',
        name: 'Defeat 5 monsters',
        requirement: { type: RequirementType.MonstersDefeated, amount: 5 },
        icon: '/powers/skull-medium.png',
        type: PowerType.Health,
        baseBonus: 0.1,
        incrementBonus: 0.1,
        maxCount: Infinity,
    },
    {
        id: 'visit-3-locations',
        name: 'Visit 3 Locations',
        requirement: { type: RequirementType.LocationsVisited, amount: 3 },
        icon: '/powers/empty.png',
        type: PowerType.TravelSpeed,
        baseBonus: 0.1,
        incrementBonus: 0.1,
        maxCount: Infinity,
    },
    {
        id: 'visit-7-locations',
        name: 'Visit 7 Locations',
        requirement: { type: RequirementType.LocationsVisited, amount: 7 },
        icon: '/powers/empty.png',
        type: PowerType.TravelSpeed,
        baseBonus: 0.2,
        incrementBonus: 0.2,
        maxCount: Infinity,
    },
];
