import type { Power } from '$lib/game/features/powers/Power';
import { RequirementType } from '$lib/game/tools/requirements/RequirementType';
import { PowerType } from '$lib/game/features/powers/PowerType';
import { AreaId } from '$lib/game/features/world/AreaId';

export const powers: Power[] = [
    {
        id: 'visit-5-riverlands',
        name: 'Visit 5 different Locations in the Riverlands',
        requirement: { type: RequirementType.RegionVisited, amount: 5, region: AreaId.Riverlands },
        icon: '/powers/riverlands.png',
        type: PowerType.TravelSpeed,
        baseBonus: 0.25,
        incrementBonus: 0.25,
        maxCount: Infinity,
    },
    {
        id: 'visit-5-mountains',
        name: 'Visit 5 different Locations in the Mountains',
        requirement: { type: RequirementType.RegionVisited, amount: 5, region: AreaId.Mountains },
        icon: '/powers/mountains.png',
        type: PowerType.Attack,
        baseBonus: 0.25,
        incrementBonus: 0.25,
        maxCount: Infinity,
    },
    {
        id: 'visit-5-forest',
        name: 'Visit 5 different Locations in the Forest',
        requirement: { type: RequirementType.RegionVisited, amount: 5, region: AreaId.Forest },
        icon: '/powers/forest.png',
        type: PowerType.Defense,
        baseBonus: 0.25,
        incrementBonus: 0.25,
        maxCount: Infinity,
    },
    {
        id: 'visit-5-desert',
        name: 'Visit 5 different Locations in the Desert',
        requirement: { type: RequirementType.RegionVisited, amount: 5, region: AreaId.Desert },
        icon: '/powers/desert.png',
        type: PowerType.Health,
        baseBonus: 0.25,
        incrementBonus: 0.25,
        maxCount: Infinity,
    },
    {
        id: 'deal-8-damage',
        name: 'Deal 8 damage',
        requirement: { type: RequirementType.DamageDealt, amount: 8 },
        icon: 'powers/weapon-small.png',
        type: PowerType.Attack,
        baseBonus: 0.05,
        incrementBonus: 0.05,
        maxCount: Infinity,
    },
    {
        id: 'deal-25-damage',
        name: 'Deal 25 damage',
        requirement: { type: RequirementType.DamageDealt, amount: 25 },
        icon: 'powers/weapon-axe.png',
        type: PowerType.Attack,
        baseBonus: 0.1,
        incrementBonus: 0.1,
        maxCount: Infinity,
    },
    {
        id: 'deal-100-damage',
        name: 'Deal 100 damage',
        requirement: { type: RequirementType.DamageDealt, amount: 100 },
        icon: 'powers/weapon-halberd.png',
        type: PowerType.Attack,
        baseBonus: 0.25,
        incrementBonus: 0.25,
        maxCount: Infinity,
    },
    {
        id: 'deal-250-damage',
        name: 'Deal 250 damage',
        requirement: { type: RequirementType.DamageDealt, amount: 250 },
        icon: 'powers/weapon-halberd.png',
        type: PowerType.Attack,
        baseBonus: 0.5,
        incrementBonus: 0.5,
        maxCount: Infinity,
    },
    {
        id: 'deal-500-damage',
        name: 'Deal 500 damage',
        requirement: { type: RequirementType.DamageDealt, amount: 500 },
        icon: 'powers/weapon-halberd.png',
        type: PowerType.Attack,
        baseBonus: 1,
        incrementBonus: 1,
        maxCount: Infinity,
    },
    {
        id: 'deal-1000-damage',
        name: 'Deal 1000 damage',
        requirement: { type: RequirementType.DamageDealt, amount: 1000 },
        icon: 'powers/weapon-halberd.png',
        type: PowerType.Attack,
        baseBonus: 2,
        incrementBonus: 2,
        maxCount: Infinity,
    },
    {
        id: 'take-5-damage',
        name: 'Take 5 damage',
        requirement: { type: RequirementType.DamageTaken, amount: 5 },
        icon: '/powers/shield-small.png',
        type: PowerType.Defense,
        baseBonus: 0.05,
        incrementBonus: 0.05,
        maxCount: Infinity,
    },
    {
        id: 'take-25-damage',
        name: 'Take 25 damage',
        requirement: { type: RequirementType.DamageTaken, amount: 25 },
        icon: '/powers/shield-medium.png',
        type: PowerType.Defense,
        baseBonus: 0.1,
        incrementBonus: 0.1,
        maxCount: Infinity,
    },
    {
        id: 'take-50-damage',
        name: 'Take 50 damage',
        requirement: { type: RequirementType.DamageTaken, amount: 50 },
        icon: '/powers/shield-heroic.png',
        type: PowerType.Defense,
        baseBonus: 0.25,
        incrementBonus: 0.25,
        maxCount: Infinity,
    },
    {
        id: 'take-100-damage',
        name: 'Take 100 damage',
        requirement: { type: RequirementType.DamageTaken, amount: 100 },
        icon: '/powers/shield-heroic.png',
        type: PowerType.Defense,
        baseBonus: 0.5,
        incrementBonus: 0.5,
        maxCount: Infinity,
    },
    {
        id: 'take-250-damage',
        name: 'Take 250 damage',
        requirement: { type: RequirementType.DamageTaken, amount: 250 },
        icon: '/powers/shield-heroic.png',
        type: PowerType.Defense,
        baseBonus: 1,
        incrementBonus: 1,
        maxCount: Infinity,
    },
    {
        id: 'take-500-damage',
        name: 'Take 500 damage',
        requirement: { type: RequirementType.DamageTaken, amount: 500 },
        icon: '/powers/shield-heroic.png',
        type: PowerType.Defense,
        baseBonus: 2,
        incrementBonus: 2,
        maxCount: Infinity,
    },
    {
        id: 'defeat-1-monster',
        name: 'Defeat 1 monster',
        requirement: { type: RequirementType.MonstersDefeated, amount: 1 },
        icon: '/powers/skull-small.png',
        type: PowerType.Health,
        baseBonus: 0.05,
        incrementBonus: 0.05,
        maxCount: Infinity,
    },
    {
        id: 'defeat-5-monsters',
        name: 'Defeat 5 monsters',
        requirement: { type: RequirementType.MonstersDefeated, amount: 5 },
        icon: '/powers/skull-medium.png',
        type: PowerType.Health,
        baseBonus: 0.1,
        incrementBonus: 0.1,
        maxCount: Infinity,
    },
    {
        id: 'defeat-15-monsters',
        name: 'Defeat 15 monsters',
        requirement: { type: RequirementType.MonstersDefeated, amount: 15 },
        icon: '/powers/skull-medium.png',
        type: PowerType.Health,
        baseBonus: 0.2,
        incrementBonus: 0.2,
        maxCount: Infinity,
    },
    {
        id: 'defeat-30-monsters',
        name: 'Defeat 30 monsters',
        requirement: { type: RequirementType.MonstersDefeated, amount: 30 },
        icon: '/powers/skull-medium.png',
        type: PowerType.Health,
        baseBonus: 0.4,
        incrementBonus: 0.4,
        maxCount: Infinity,
    },
    {
        id: 'defeat-50-monsters',
        name: 'Defeat 50 monsters',
        requirement: { type: RequirementType.MonstersDefeated, amount: 50 },
        icon: '/powers/skull-medium.png',
        type: PowerType.Health,
        baseBonus: 0.4,
        incrementBonus: 0.4,
        maxCount: Infinity,
    },
    {
        id: 'defeat-100-monsters',
        name: 'Defeat 100 monsters',
        requirement: { type: RequirementType.MonstersDefeated, amount: 100 },
        icon: '/powers/skull-medium.png',
        type: PowerType.Health,
        baseBonus: 1,
        incrementBonus: 1,
        maxCount: Infinity,
    },
    {
        id: 'visit-3-locations',
        name: 'Visit 3 different Locations',
        requirement: { type: RequirementType.LocationsVisited, amount: 3 },
        icon: '/powers/empty.png',
        type: PowerType.TravelSpeed,
        baseBonus: 0.1,
        incrementBonus: 0.1,
        maxCount: Infinity,
    },
    {
        id: 'visit-5-locations',
        name: 'Visit 5 different Locations',
        requirement: { type: RequirementType.LocationsVisited, amount: 5 },
        icon: '/powers/empty.png',
        type: PowerType.TravelSpeed,
        baseBonus: 0.2,
        incrementBonus: 0.2,
        maxCount: Infinity,
    },
    {
        id: 'visit-7-locations',
        name: 'Visit 7 different Locations',
        requirement: { type: RequirementType.LocationsVisited, amount: 7 },
        icon: '/powers/empty.png',
        type: PowerType.TravelSpeed,
        baseBonus: 0.5,
        incrementBonus: 0.5,
        maxCount: Infinity,
    },
    {
        id: 'visit-10-locations',
        name: 'Visit 10 different Locations',
        requirement: { type: RequirementType.LocationsVisited, amount: 10 },
        icon: '/powers/empty.png',
        type: PowerType.TravelSpeed,
        baseBonus: 1,
        incrementBonus: 1,
        maxCount: Infinity,
    },
    {
        id: 'visit-20-locations',
        name: 'Visit 20 different Locations',
        requirement: { type: RequirementType.LocationsVisited, amount: 20 },
        icon: '/powers/empty.png',
        type: PowerType.TravelSpeed,
        baseBonus: 2,
        incrementBonus: 2,
        maxCount: Infinity,
    },
    {
        id: 'visit-all-regions',
        name: 'Visit all regions',
        requirement: { type: RequirementType.AllRegionsVisited },
        icon: '/powers/all.png',
        type: PowerType.CombatSpeed,
        baseBonus: 0.1,
        incrementBonus: 0.1,
        maxCount: Infinity,
    },
];
