export type PowerId =
    | 'deal-5-damage'
    | 'deal-20-damage'
    | 'deal-50-damage'
    | 'deal-1000-damage'
    | 'take-5-damage'
    | 'take-20-damage'
    | 'take-50-damage'
    | 'take-1000-damage'
    | 'defeat-1-monster'
    | 'defeat-5-monsters'
    | 'defeat-10-monsters'
    | 'defeat-100-monsters'
    | 'visit-3-locations'
    | 'visit-7-locations';
